# Generated by Django 6.0.2 on 2026-03-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(max_length=150)),
                ('empId', models.IntegerField()),
                ('designation', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('phoneNo', models.IntegerField()),
            ],
        ),
    ]
