# Generated by Django 6.0.2 on 2026-03-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=150)),
                ('phoneNumber', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('customerType', models.CharField(max_length=150)),
            ],
        ),
    ]
